### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by kkkparty** [Q-Qing/huawei_digix2021_track1#1]
您好，我是小白，想好好学习一下您的代码，方便提供一下数据集，以及数据处理的代码吗？谢谢！

**Comment by Q-Qing** [comment]
上传了部分数据，以及数据处理的代码，建议配合官方的数据说明文档使用

**Comment by kkkparty** [comment]
非常感谢大佬无私的分享，respect!



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月10日(周三) 上午10:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Q-Qing/huawei_digix2021_track1] 数据集问题 (Issue #1)




 
上传了部分数据，以及数据处理的代码，建议配合官方的数据说明文档使用
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
