### ISSUE TITLE
请教学习

### ISSUE THREAD

**Issue by hi-tomorrow** [Q-Qing/huawei_digix2021_track1#2]
学长好！我是上交电气的学生，之前也参加了DIGIX竞赛，非常有幸能通过GitHub学习到更优秀的方法。看了学长的代码，其中有几个问题想请教学习：
1.看代码中没有看到使用music/artist相关的特征?（如考虑到平台的歌曲库有限，经常听同一歌手或同一歌曲的用户是否在留存方面有相同之处） 
2.在训练和预测模型py中，使用的是final_processed_data而非processed_data，请问final_processed_data是如何处理得到的？
若涉及到相关竞赛数据保密性，方便的话可以私戳我wx(wyj_qqg)或qq(852355299)吗？非常感谢~

**Comment by Q-Qing** [comment]
最终的模型没有利用到歌曲和歌手的信息。其实是可以利用图神经网络将这部分信息也融合到模型中去的，这样说不定会有更好的效果，只是受限于时间，我没有来得及这么做。另外final_processed_data和processed_data只是文件名称不同而已，数据处理的方法是一样的。

**Comment by hi-tomorrow** [comment]
了解！非常感谢耐心解答~
