### ISSUE TITLE
您好，数据集能否提供一下，想学习一下您的模型

### ISSUE THREAD

**Issue by kaileby** [Q-Qing/huawei_digix2021_track1#3]

**Comment by Q-Qing** [comment]
数据集请参见比赛的官网

**Comment by kaileby** [comment]
谢谢您得答复，官网下载不了了，所以才能问一下您

**Comment by Q-Qing** [comment]
数据集太大，我没有办法全部上传到github上。在sub_dataset文件里我提供了部分文件的小部分数据，你可以参考官网的数据文件说明，以及data_process里的代码学习数据处理的过程，这些可以帮助你理解最终模型输入的数据。

**Comment by kaileby** [comment]
感谢您得及时回复。模型思想大致理解了，想跑一下模型 p5_edrnn_teain.py，其中提到的文件：
![image](https://user-images.githubusercontent.com/21981735/149262268-2f0b137d-c591-4fce-b54a-f219d554b71f.png)
如何获取？

**Comment by kaileby** [comment]
感谢您的耐心回复。模型思想大致理解了，想跑一下 p5_edrnn_train.py 文件，其中需要的数据如何获取？
![image](https://user-images.githubusercontent.com/21981735/149262412-a3daa2c7-7a70-4739-a9c0-b083716b7ee8.png)

**Comment by kaileby** [comment]
这是我找到的本项目的官方数据，有需要的朋友自取：链接：https://pan.baidu.com/s/16HkxORNRTgXkaD-6EzensA 
提取码：364g

**Comment by Q-Qing** [comment]
截图所示的文件都是对原始数据做完处理后的文件，按照data_process中文件的标号依次运行程序就可以得到这些文件。

**Comment by kaileby** [comment]
好的好的，谢谢您，这回复太快了，哈哈哈

**Comment by kaileby** [comment]
star走起

**Comment by kaileby** [comment]
试着跑了一下，data_subset中有些文件没有提供完整，跑不通，能否上传一下这三个文件？
![image](https://user-images.githubusercontent.com/21981735/149264470-a1bfcd93-8dc0-487e-a4bd-f89de856c55e.png)

**Comment by Q-Qing** [comment]
这三个文件是对原始文件的整合处理得到的，你需要运行data_process文件夹下的程序才可以得到这些文件。你要把原始数据放到data_process中程序里指定的文件夹下，才能运行数据处理的程序。
