### ISSUE TITLE
Parallel_ED_RNN.train_model里面predict n days

### ISSUE THREAD

**Issue by aesdhj** [Q-Qing/huawei_digix2021_track1#5]
大佬，这几天看你的代码学习了很多东西，谢谢。
然后请教你几个问题，就是Parallel_ED_RNN.train_model里面predict n days
从select_day来看Counter({0: 29, 1: 28, 2: 28, 6: 1, 13: 1, 29: 1})（label的次数），这个比例是线下实验出来的还是predict n days有什么内在的逻辑，谢谢

**Comment by Q-Qing** [comment]
没有太理解你的问题。这个比赛的数据集有60天，然后是要预测未来30天用户用户的使用情况，然后选择1，2，3，7，14，30这六天的预测值来评价模型的好坏。正常的训练集测试集划分是前30天训练后30天测试，但这样会浪费后面30天的数据。所以我代码里实现的是一个滑动的预测，通过缩短预测窗口的方法来增加训练数据。

**Comment by aesdhj** [comment]
> 

这个滑动预测是怎么确定的，想问这个，可能我说的不是很清楚，我看你代码里面注释掉了predict 14 days和predict 7 days，谢谢

**Comment by Q-Qing** [comment]
这个是试出来，预测的窗口越长相应的能利用的训练集也就越少。最后的实验结果是在预测30天的同时，滑动地向后预测未来3天效果最好。

**Comment by aesdhj** [comment]
> 

谢谢，感谢你这么快速的解答
